# Generated by Django 4.2.7 on 2025-09-05 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kilograms', max_digits=10, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUED', 'Discontinued'), ('UNDER_REVIEW', 'Under Review')], default='ACTIVE', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('expected_lifespan', models.IntegerField(blank=True, help_text='Expected lifespan in months', null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('railway_zone', models.CharField(blank=True, max_length=100)),
                ('railway_division', models.CharField(blank=True, max_length=100)),
                ('track_section', models.CharField(blank=True, max_length=100)),
                ('kilometer_marker', models.CharField(blank=True, max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_data', models.CharField(max_length=500, unique=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'parts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('ROUTINE', 'Routine Maintenance'), ('REPAIR', 'Repair'), ('REPLACEMENT', 'Replacement'), ('INSPECTION', 'Inspection'), ('CLEANING', 'Cleaning'), ('CALIBRATION', 'Calibration')], max_length=20)),
                ('description', models.TextField()),
                ('performed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='parts.part')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Part Maintenance Record',
                'verbose_name_plural': 'Part Maintenance Records',
                'db_table': 'part_maintenance_records',
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parts/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.part')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Part Image',
                'verbose_name_plural': 'Part Images',
                'db_table': 'part_images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PartDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('MANUAL', 'User Manual'), ('CERTIFICATE', 'Certificate'), ('WARRANTY', 'Warranty'), ('INSPECTION', 'Inspection Report'), ('MAINTENANCE', 'Maintenance Record'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='parts/documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parts.part')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Part Document',
                'verbose_name_plural': 'Part Documents',
                'db_table': 'part_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='parts.partcategory')),
            ],
            options={
                'verbose_name': 'Part Category',
                'verbose_name_plural': 'Part Categories',
                'db_table': 'part_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='parts.partcategory'),
        ),
        migrations.AddField(
            model_name='part',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='part',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='parts.part')),
            ],
            options={
                'verbose_name': 'Part Specification',
                'verbose_name_plural': 'Part Specifications',
                'db_table': 'part_specifications',
                'unique_together': {('part', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['part_number'], name='parts_part_nu_af7709_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['qr_code_data'], name='parts_qr_code_451d21_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['status'], name='parts_status_81e5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='parts_categor_5e1266_idx'),
        ),
    ]
