# Generated by Django 4.2.7 on 2025-09-05 05:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('ADMIN', 'System Administrator'), ('RAILWAY_AUTHORITY', 'Railway Authority'), ('RAILWAY_EMPLOYEE', 'Railway Employee'), ('VENDOR', 'Vendor'), ('INSPECTOR', 'Quality Inspector'), ('MANAGER', 'Project Manager')], default='RAILWAY_EMPLOYEE', help_text='Type of user in the system', max_length=20)),
                ('employee_id', models.CharField(blank=True, help_text='Unique employee identification number', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')])),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(blank=True, help_text='Department or division within the organization', max_length=100)),
                ('designation', models.CharField(blank=True, help_text='Job title or designation', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user account has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, help_text='Brief description about the user', max_length=500)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15)),
                ('authority_level', models.CharField(blank=True, choices=[('ZONAL', 'Zonal Authority'), ('DIVISIONAL', 'Divisional Authority'), ('REGIONAL', 'Regional Authority'), ('NATIONAL', 'National Authority')], help_text='Authority level for railway authorities', max_length=50)),
                ('jurisdiction', models.CharField(blank=True, help_text='Geographical jurisdiction or area of responsibility', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Company name for vendors', max_length=200)),
                ('company_registration', models.CharField(blank=True, help_text='Company registration number', max_length=50)),
                ('vendor_category', models.CharField(blank=True, choices=[('TRACK_COMPONENTS', 'Track Components'), ('SIGNALING', 'Signaling Equipment'), ('ELECTRICAL', 'Electrical Equipment'), ('MECHANICAL', 'Mechanical Equipment'), ('SAFETY', 'Safety Equipment'), ('GENERAL', 'General Supplies')], help_text='Category of vendor business', max_length=100)),
                ('railway_zone', models.CharField(blank=True, help_text='Railway zone for employees', max_length=100)),
                ('railway_division', models.CharField(blank=True, help_text='Railway division for employees', max_length=100)),
                ('work_location', models.CharField(blank=True, help_text='Current work location', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
