# Generated by Django 4.2.7 on 2025-09-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('RAILWAY_AUTHORITY', 'Railway Authority'), ('VENDOR', 'Vendor'), ('RAILWAY_WORKER', 'Railway Worker'), ('SOFTWARE_STAFF', 'Software Staff/Moderator')], default='VENDOR', help_text='Type of user in the system', max_length=20),
        ),
    ]
