# Generated by Django 4.2.7 on 2025-09-05 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=200)),
                ('jurisdiction', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Railway Division',
                'verbose_name_plural': 'Railway Divisions',
                'db_table': 'railway_divisions',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RailwayZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('headquarters', models.CharField(max_length=200)),
                ('jurisdiction', models.TextField(help_text='Geographical jurisdiction')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Railway Zone',
                'verbose_name_plural': 'Railway Zones',
                'db_table': 'railway_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TRACK_COMPONENTS', 'Track Components'), ('SIGNALING', 'Signaling Equipment'), ('ELECTRICAL', 'Electrical Equipment'), ('MECHANICAL', 'Mechanical Equipment'), ('SAFETY', 'Safety Equipment'), ('COMMUNICATION', 'Communication Equipment'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('track_section', models.CharField(blank=True, max_length=100)),
                ('kilometer_marker', models.CharField(blank=True, max_length=50)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications in JSON format')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='pieces', max_length=50)),
                ('deadline_days', models.PositiveIntegerField(help_text='Number of days to complete the requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('INSTALLED', 'Installed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INACTIVE', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/requirements/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vendor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'RAILWAY_AUTHORITY'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_requirements', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='railway.railwaydivision')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='railway.railwayzone')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'db_table': 'requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('INSTALLED', 'Installed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('INSTALLED', 'Installed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='railway.requirement')),
            ],
            options={
                'verbose_name': 'Requirement Status History',
                'verbose_name_plural': 'Requirement Status Histories',
                'db_table': 'requirement_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('PRE_SHIPMENT', 'Pre-Shipment Inspection'), ('POST_DELIVERY', 'Post-Delivery Inspection'), ('PRE_INSTALLATION', 'Pre-Installation Inspection'), ('POST_INSTALLATION', 'Post-Installation Inspection'), ('FINAL', 'Final Inspection')], max_length=20)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('CONDITIONAL_PASS', 'Conditional Pass'), ('REQUIRES_RETEST', 'Requires Retest')], max_length=20)),
                ('findings', models.TextField()),
                ('quality_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Quality rating out of 10', max_digits=3, null=True)),
                ('issues_found', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs taken during inspection')),
                ('documents', models.JSONField(blank=True, default=list, help_text='List of document URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_requirement_inspections', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='railway.requirement')),
            ],
            options={
                'verbose_name': 'Requirement Inspection',
                'verbose_name_plural': 'Requirement Inspections',
                'db_table': 'requirement_inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddField(
            model_name='railwaydivision',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='railway.railwayzone'),
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivery_time_days', models.PositiveIntegerField(help_text='Proposed delivery time in days')),
                ('proposal_description', models.TextField()),
                ('technical_specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications proposed by vendor')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to='railway.requirement')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'RAILWAY_AUTHORITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Request',
                'verbose_name_plural': 'Vendor Requests',
                'db_table': 'vendor_requests',
                'ordering': ['-created_at'],
                'unique_together': {('requirement', 'vendor')},
            },
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['requirement_id'], name='requirement_require_d528d1_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['status'], name='requirement_status_b8bfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['zone', 'division'], name='requirement_zone_id_2921ea_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['created_by'], name='requirement_created_e6754f_idx'),
        ),
    ]
