# Generated by Django 4.2.7 on 2025-09-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.CharField(choices=[('TRACK_CLIPS', 'Track Clips'), ('LINERS', 'Liners'), ('TRACK_PADS', 'Track Pads')], max_length=20),
        ),
        migrations.CreateModel(
            name='RailwayLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('STATION', 'Station'), ('JUNCTION', 'Junction'), ('YARD', 'Yard'), ('DEPOT', 'Depot'), ('SIGNAL_CABIN', 'Signal Cabin'), ('BRIDGE', 'Bridge'), ('TUNNEL', 'Tunnel'), ('OTHER', 'Other')], default='STATION', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='railway.railwaydivision')),
            ],
            options={
                'verbose_name': 'Railway Location',
                'verbose_name_plural': 'Railway Locations',
                'db_table': 'railway_locations',
                'ordering': ['division', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='requirement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='railway.railwaylocation'),
        ),
    ]
