# Generated by Django 4.2.7 on 2025-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_alter_requirement_category_railwaylocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Pound Sterling (GBP)'), ('JPY', 'Japanese Yen (JPY)')], default='INR', max_length=3),
        ),
    ]
