# Generated by Django 4.2.7 on 2025-09-05 16:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railway', '0003_alter_requirement_currency'),
        ('parts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspection Checklist Item',
                'verbose_name_plural': 'Inspection Checklist Items',
                'db_table': 'inspection_checklist',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stage_type', models.CharField(choices=[('MANUFACTURING', 'Manufacturing Stage'), ('SUPPLY', 'Supply Stage'), ('RECEIVING', 'Receiving Stage'), ('FITTING', 'Fitting/Track Installation Stage'), ('FINAL', 'Final Inspection Stage')], max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('requires_vendor', models.BooleanField(default=False)),
                ('requires_receiver', models.BooleanField(default=False)),
                ('requires_railway_auth', models.BooleanField(default=False)),
                ('requires_worker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspection Stage',
                'verbose_name_plural': 'Inspection Stages',
                'db_table': 'inspection_stages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnlineInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('CONDITIONAL_PASS', 'Conditional Pass'), ('REQUIRES_RETEST', 'Requires Retest')], max_length=20, null=True)),
                ('quality_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Quality rating out of 10', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall inspection score out of 100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('findings', models.TextField(blank=True)),
                ('issues_found', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('overview_notes', models.TextField(blank=True, help_text='Optional overview notes from inspector')),
                ('inspection_location', models.CharField(max_length=200)),
                ('railway_zone', models.CharField(blank=True, max_length=100)),
                ('railway_division', models.CharField(blank=True, max_length=100)),
                ('track_section', models.CharField(blank=True, max_length=100)),
                ('kilometer_marker', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_training_data_json', models.JSONField(blank=True, default=dict, help_text='Data for AI model training')),
                ('ai_summary_generated', models.BooleanField(default=False)),
                ('ai_summary_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_inspections', to='orders.purchaseorder')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_inspections', to='parts.part')),
                ('railway_auth', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'RAILWAY_AUTHORITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='railway_auth_inspections', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'RAILWAY_AUTHORITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_inspections', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_inspections', to='railway.requirement')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspections.inspectionstage')),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_inspections', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'RAILWAY_WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Inspection',
                'verbose_name_plural': 'Online Inspections',
                'db_table': 'online_inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('key_findings', models.JSONField(default=list, help_text='Key findings from the inspection')),
                ('quality_assessment', models.TextField()),
                ('recommendations', models.JSONField(default=list, help_text='AI-generated recommendations')),
                ('risk_assessment', models.JSONField(default=dict, help_text='Risk assessment data')),
                ('ai_model_version', models.CharField(max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-1)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary_record', to='inspections.onlineinspection')),
            ],
            options={
                'verbose_name': 'Inspection Summary',
                'verbose_name_plural': 'Inspection Summaries',
                'db_table': 'inspection_summaries',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('OVERVIEW', 'Overview Photo'), ('DETAIL', 'Detail Photo'), ('ISSUE', 'Issue Photo'), ('COMPLETION', 'Completion Photo'), ('DOCUMENT', 'Document Photo'), ('OTHER', 'Other')], default='OVERVIEW', max_length=20)),
                ('image', models.ImageField(help_text='Upload inspection photos', upload_to='inspections/photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='AI analysis results for this photo')),
                ('ai_tags', models.JSONField(blank=True, default=list, help_text='AI-generated tags for this photo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.onlineinspection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_inspection_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Photo',
                'verbose_name_plural': 'Inspection Photos',
                'db_table': 'inspection_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('REPORT', 'Report'), ('MANUAL', 'Manual'), ('WARRANTY', 'Warranty'), ('TEST_RESULT', 'Test Result'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Upload inspection documents', upload_to='inspections/documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspections.onlineinspection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_inspection_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Document',
                'verbose_name_plural': 'Inspection Documents',
                'db_table': 'inspection_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('N/A', 'Not Applicable'), ('PENDING', 'Pending')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspectionchecklist')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='inspections.onlineinspection')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_responses', to='inspections.inspectionphoto')),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Checklist Response',
                'verbose_name_plural': 'Inspection Checklist Responses',
                'db_table': 'inspection_checklist_responses',
                'ordering': ['checklist_item__order'],
            },
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='inspections.inspectionstage'),
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_data', models.JSONField(default=dict, help_text='Stage-specific training data')),
                ('photo_analysis', models.JSONField(default=dict, help_text='Photo analysis data for AI training')),
                ('quality_metrics', models.JSONField(default=dict, help_text='Quality metrics for AI training')),
                ('defect_patterns', models.JSONField(default=dict, help_text='Defect patterns identified')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_training_records', to='inspections.onlineinspection')),
            ],
            options={
                'verbose_name': 'AI Training Data',
                'verbose_name_plural': 'AI Training Data',
                'db_table': 'ai_training_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='onlineinspection',
            index=models.Index(fields=['stage', 'status'], name='online_insp_stage_i_a149da_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineinspection',
            index=models.Index(fields=['requirement', 'stage'], name='online_insp_require_c7a7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineinspection',
            index=models.Index(fields=['part', 'stage'], name='online_insp_part_id_20c2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineinspection',
            index=models.Index(fields=['inspection_date'], name='online_insp_inspect_628418_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionchecklistresponse',
            unique_together={('inspection', 'checklist_item')},
        ),
    ]
