# Generated by Django 4.2.7 on 2025-09-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='onlineinspection',
            name='online_insp_part_id_20c2ec_idx',
        ),
    ]
