# Generated by Django 4.2.7 on 2025-09-05 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('railway', '0003_alter_requirement_currency'),
        ('inspections', '0002_remove_onlineinspection_online_insp_part_id_20c2ec_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionphoto',
            name='ai_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score for this photo analysis', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='inspectionphoto',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inspectionphoto',
            name='qr_code_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineinspection',
            name='inspection_source',
            field=models.CharField(choices=[('VENDOR', 'Vendor Side'), ('RAILWAY_AUTH', 'Railway Authority Side'), ('WORKER', 'Worker Side')], default='VENDOR', help_text='Which side conducted this inspection', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionphoto',
            name='photo_type',
            field=models.CharField(choices=[('EQUIPMENT_OVERVIEW', 'Equipment Overview'), ('EQUIPMENT_DETAIL', 'Equipment Detail'), ('QR_CODE', 'QR Code Scan'), ('DEFECT', 'Defect Found'), ('COMPLETION', 'Completion Photo'), ('DOCUMENT', 'Document Photo'), ('OTHER', 'Other')], default='EQUIPMENT_OVERVIEW', max_length=20),
        ),
        migrations.CreateModel(
            name='EquipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('SUPPLY', 'Supply'), ('RECEIVING', 'Receiving'), ('FITTING', 'Fitting/Installation'), ('FINAL', 'Final Inspection'), ('COMPLETED', 'Completed')], default='MANUFACTURING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_batches', to='parts.part')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_batches', to='railway.requirement')),
            ],
            options={
                'verbose_name': 'Equipment Batch',
                'verbose_name_plural': 'Equipment Batches',
                'db_table': 'equipment_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISmartReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('quality_assessment', models.TextField()),
                ('defect_analysis', models.JSONField(default=dict, help_text='Analysis of defects found across all inspection stages')),
                ('stage_comparison', models.JSONField(default=dict, help_text='Comparison of quality across different stages')),
                ('recommendations', models.JSONField(default=list, help_text='AI-generated recommendations')),
                ('risk_assessment', models.JSONField(default=dict, help_text='Risk assessment data')),
                ('compliance_status', models.JSONField(default=dict, help_text='Compliance status with standards')),
                ('vendor_inspections', models.JSONField(default=list, help_text='Data from vendor-side inspections')),
                ('railway_auth_inspections', models.JSONField(default=list, help_text='Data from railway authority inspections')),
                ('worker_inspections', models.JSONField(default=list, help_text='Data from worker-side inspections')),
                ('ai_model_version', models.CharField(max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-1)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('processing_time_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='inspections.equipmentbatch')),
            ],
            options={
                'verbose_name': 'AI Smart Report',
                'verbose_name_plural': 'AI Smart Reports',
                'db_table': 'ai_smart_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='onlineinspection',
            name='equipment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.equipmentbatch'),
        ),
    ]
