# Generated by Django 4.2.7 on 2025-09-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_alter_requirement_currency'),
        ('inspections', '0003_inspectionphoto_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbatch',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Unique batch number for this equipment batch', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inspectionphoto',
            name='equipment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.equipmentbatch'),
        ),
        migrations.AlterField(
            model_name='equipmentbatch',
            name='equipment_type',
            field=models.CharField(choices=[('LINERS', 'Liners'), ('PADS', 'Pads'), ('CLIPS', 'Clips')], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentbatch',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_batches', to='railway.requirement'),
        ),
    ]
