# Generated by Django 4.2.7 on 2025-09-05 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=50, unique=True)),
                ('check_type', models.CharField(choices=[('INCOMING', 'Incoming Quality Check'), ('IN_PROCESS', 'In-Process Quality Check'), ('FINAL', 'Final Quality Check'), ('RANDOM', 'Random Quality Check'), ('CUSTOMER_COMPLAINT', 'Customer Complaint Check')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('REQUIRES_RETEST', 'Requires Retest')], default='PENDING', max_length=20)),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('non_conformities', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('preventive_actions', models.TextField(blank=True)),
                ('test_results', models.JSONField(blank=True, default=dict, help_text='Test results in JSON format')),
                ('certificates', models.JSONField(blank=True, default=list, help_text='List of certificate URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_quality_checks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='orders.purchaseorder')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='parts.part')),
            ],
            options={
                'verbose_name': 'Quality Check',
                'verbose_name_plural': 'Quality Checks',
                'db_table': 'quality_checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('ROUTINE', 'Routine Inspection'), ('PERIODIC', 'Periodic Inspection'), ('PRE_INSTALLATION', 'Pre-Installation'), ('POST_INSTALLATION', 'Post-Installation'), ('DEFECT_INSPECTION', 'Defect Inspection'), ('SAFETY_INSPECTION', 'Safety Inspection'), ('QUALITY_INSPECTION', 'Quality Inspection')], max_length=20)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('CONDITIONAL_PASS', 'Conditional Pass'), ('REQUIRES_ATTENTION', 'Requires Attention')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Inspection score out of 100', max_digits=5, null=True)),
                ('findings', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('defects_found', models.TextField(blank=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('corrective_actions_required', models.BooleanField(default=False)),
                ('corrective_actions', models.TextField(blank=True)),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to='inspections/reports/')),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs taken during inspection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='parts.part')),
            ],
            options={
                'verbose_name': 'Inspection Record',
                'verbose_name_plural': 'Inspection Records',
                'db_table': 'inspection_records',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MANUFACTURED', 'Manufactured'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('INSTALLED', 'Installed'), ('INSPECTED', 'Inspected'), ('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('REPLACED', 'Replaced'), ('DECOMMISSIONED', 'Decommissioned'), ('LOCATION_CHANGE', 'Location Changed'), ('STATUS_CHANGE', 'Status Changed')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('railway_zone', models.CharField(blank=True, max_length=100)),
                ('railway_division', models.CharField(blank=True, max_length=100)),
                ('track_section', models.CharField(blank=True, max_length=100)),
                ('kilometer_marker', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='parts.part')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_events', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'db_table': 'tracking_events',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['part', 'event_date'], name='tracking_ev_part_id_3be7d7_idx'), models.Index(fields=['event_type', 'event_date'], name='tracking_ev_event_t_470040_idx'), models.Index(fields=['location'], name='tracking_ev_locatio_55b33a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx'), models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('MAINTENANCE_DUE', 'Maintenance Due'), ('INSPECTION_DUE', 'Inspection Due'), ('WARRANTY_EXPIRING', 'Warranty Expiring'), ('PART_FAILURE', 'Part Failure'), ('QUALITY_ISSUE', 'Quality Issue'), ('DELIVERY_DELAY', 'Delivery Delay'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('SYSTEM_ERROR', 'System Error')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='ACTIVE', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='orders.purchaseorder')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parts.part')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='alerts_status_976bbd_idx'), models.Index(fields=['alert_type', 'created_at'], name='alerts_alert_t_28b6d7_idx')],
            },
        ),
    ]
